"""
Webhook Security - Signature Verification and Validation
=========================================================

Provides webhook security utilities including HMAC-SHA256 signature generation
and verification, payload validation, and timestamp checking to prevent replay attacks.

Design Principles:
- HMAC-SHA256 for cryptographic signature verification
- Timing-safe comparison to prevent timing attacks
- Constant-time comparison for signature validation
- Graceful handling of missing/invalid signatures
- Support for multiple signature versions

Security Features:
- HMAC-SHA256 signature generation
- Timing-safe signature verification
- Payload integrity validation
- Protection against replay attacks
- Support for signature versioning
"""

from __future__ import annotations

import hashlib
import hmac
import json
from datetime import UTC, datetime
from typing import Any

# Import configuration constants
from integrations.webhooks.config import (
    SIGNATURE_HEADER,
    SIGNATURE_VERSION,
)


class WebhookSecurityError(Exception):
    """Base exception for webhook security errors."""

    pass


class InvalidSignatureError(WebhookSecurityError):
    """Exception raised when webhook signature is invalid."""

    pass


class MissingSignatureError(WebhookSecurityError):
    """Exception raised when webhook signature is missing."""

    pass


class ExpiredSignatureError(WebhookSecurityError):
    """Exception raised when webhook signature timestamp is too old."""

    pass


def generate_signature(
    payload: dict[str, Any],
    secret: str,
) -> str:
    """
    Generate HMAC-SHA256 signature for webhook payload.

    The signature is generated by:
    1. Converting payload to JSON string without whitespace
    2. Computing HMAC-SHA256 hash using the secret
    3. Prefixing with version identifier

    Args:
        payload: JSON payload to sign
        secret: Secret key for signature generation

    Returns:
        Signature string with version prefix (e.g., "v1=abc123...")

    Example:
        >>> payload = {"event": "spec.created", "data": {...}}
        >>> secret = "my_webhook_secret"
        >>> signature = generate_signature(payload, secret)
        >>> print(signature)
        v1=abc123def456...
    """
    # Convert payload to JSON string without whitespace
    # Using separators ensures consistent serialization
    payload_str = json.dumps(payload, separators=(",", ":"))

    # Generate HMAC-SHA256 signature
    # hmac.new(key, msg, digestmod) returns an HMAC object
    signature_bytes = hmac.new(
        secret.encode(),
        payload_str.encode(),
        hashlib.sha256,
    ).hexdigest()

    # Return with version prefix for forward compatibility
    return f"{SIGNATURE_VERSION}={signature_bytes}"


def verify_webhook_signature(
    payload: dict[str, Any],
    signature: str,
    secret: str,
    *,
    raise_on_error: bool = False,
) -> bool:
    """
    Verify webhook signature using timing-safe comparison.

    Uses hmac.compare_digest() to prevent timing attacks that could
    leak information about the signature comparison process.

    Args:
        payload: JSON payload to verify
        signature: Signature string from webhook header
        secret: Secret key for verification
        raise_on_error: If True, raise exceptions on errors; if False, return False

    Returns:
        True if signature is valid, False otherwise

    Raises:
        MissingSignatureError: If signature is empty and raise_on_error=True
        InvalidSignatureError: If signature doesn't match and raise_on_error=True

    Example:
        >>> payload = {"event": "spec.created", "data": {...}}
        >>> signature = request.headers.get("X-Auto-Clause-Signature")
        >>> is_valid = verify_webhook_signature(payload, signature, secret)
        >>> if not is_valid:
        ...     return "Invalid signature", 403
    """
    # Check for missing signature
    if not signature:
        if raise_on_error:
            raise MissingSignatureError(
                f"Webhook signature header '{SIGNATURE_HEADER}' is missing"
            )
        return False

    # Generate expected signature
    expected_signature = generate_signature(payload, secret)

    # Use timing-safe comparison to prevent timing attacks
    # hmac.compare_digest() is designed for this purpose
    is_valid = hmac.compare_digest(expected_signature, signature)

    if not is_valid and raise_on_error:
        raise InvalidSignatureError(
            "Webhook signature verification failed. "
            "The payload may have been tampered with or the secret is incorrect."
        )

    return is_valid


def verify_webhook_timestamp(
    timestamp: str | float | int | None,
    *,
    max_age_seconds: int = 300,
    raise_on_error: bool = False,
) -> bool:
    """
    Verify webhook timestamp to prevent replay attacks.

    Checks that the webhook timestamp is not too far in the past
    or future to prevent replay attacks.

    Args:
        timestamp: Timestamp from webhook (ISO string, Unix timestamp, or None)
        max_age_seconds: Maximum allowed age in seconds (default: 5 minutes)
        raise_on_error: If True, raise exceptions on errors; if False, return False

    Returns:
        True if timestamp is valid, False otherwise

    Raises:
        MissingSignatureError: If timestamp is missing and raise_on_error=True
        ExpiredSignatureError: If timestamp is too old or in the future

    Note:
        This is optional protection. Webhooks can still be secure with
        just signature verification if timestamp checking is not needed.
    """
    if timestamp is None:
        # Timestamp is optional - don't fail if missing
        return True

    try:
        # Convert to datetime
        if isinstance(timestamp, str):
            # Parse ISO format timestamp
            webhook_time = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
        elif isinstance(timestamp, (int, float)):
            # Convert Unix timestamp
            webhook_time = datetime.fromtimestamp(timestamp, tz=UTC)
        else:
            if raise_on_error:
                raise InvalidSignatureError(
                    f"Invalid timestamp type: {type(timestamp)}"
                )
            return False

        # Get current time
        current_time = datetime.now(UTC)

        # Calculate age difference
        age_seconds = (current_time - webhook_time).total_seconds()

        # Check if timestamp is too far in the past (replay attack)
        if abs(age_seconds) > max_age_seconds:
            if raise_on_error:
                direction = "old" if age_seconds > 0 else "far in the future"
                raise ExpiredSignatureError(
                    f"Webhook timestamp is too {direction}. "
                    f"Age: {abs(age_seconds):.0f}s, maximum allowed: {max_age_seconds}s"
                )
            return False

        return True

    except (ValueError, OSError) as e:
        if raise_on_error:
            raise InvalidSignatureError(f"Invalid timestamp format: {e}") from e
        return False


def parse_signature_header(
    signature_header: str,
) -> tuple[str, str] | None:
    """
    Parse signature header to extract version and signature.

    Signature headers follow the format: "version=signature"
    Example: "v1=abc123def456..."

    Args:
        signature_header: Raw signature header string

    Returns:
        Tuple of (version, signature) or None if invalid format

    Example:
        >>> header = "v1=abc123def456..."
        >>> version, signature = parse_signature_header(header)
        >>> print(version)
        v1
        >>> print(signature)
        abc123def456...
    """
    if not signature_header:
        return None

    # Split on first '=' to separate version from signature
    parts = signature_header.split("=", 1)

    if len(parts) != 2:
        return None

    version, signature = parts

    # Validate both parts are non-empty
    if not version or not signature:
        return None

    return version, signature


def validate_webhook_payload(
    payload: dict[str, Any],
    signature: str | None,
    secret: str,
    *,
    timestamp: str | float | int | None = None,
    max_age_seconds: int = 300,
    raise_on_error: bool = False,
) -> bool:
    """
    Perform complete webhook payload validation.

    Validates both signature and timestamp (if provided) for comprehensive
    webhook security.

    Args:
        payload: JSON payload to validate
        signature: Signature string from webhook header
        secret: Secret key for validation
        timestamp: Optional timestamp for replay attack prevention
        max_age_seconds: Maximum allowed timestamp age in seconds
        raise_on_error: If True, raise exceptions on errors; if False, return False

    Returns:
        True if all validations pass, False otherwise

    Raises:
        MissingSignatureError: If signature is missing and raise_on_error=True
        InvalidSignatureError: If signature doesn't match and raise_on_error=True
        ExpiredSignatureError: If timestamp is invalid and raise_on_error=True

    Example:
        >>> payload = request.get_json()
        >>> signature = request.headers.get("X-Auto-Clause-Signature")
        >>> timestamp = request.headers.get("X-Auto-Clause-Timestamp")
        >>>
        >>> is_valid = validate_webhook_payload(
        ...     payload,
        ...     signature,
        ...     WEBHOOK_SECRET,
        ...     timestamp=timestamp,
        ...     raise_on_error=True
        ... )
    """
    # Verify signature (required)
    if not verify_webhook_signature(
        payload,
        signature or "",
        secret,
        raise_on_error=raise_on_error,
    ):
        return False

    # Verify timestamp (optional)
    if timestamp is not None and not verify_webhook_timestamp(
        timestamp,
        max_age_seconds=max_age_seconds,
        raise_on_error=raise_on_error,
    ):
        return False

    return True


def generate_signature_headers(
    payload: dict[str, Any],
    secret: str,
    *,
    include_timestamp: bool = True,
) -> dict[str, str]:
    """
    Generate headers for signed webhook request.

    Creates the necessary headers for sending a signed webhook,
    optionally including a timestamp for replay attack prevention.

    Args:
        payload: JSON payload to sign
        secret: Secret key for signature generation
        include_timestamp: Whether to include timestamp header

    Returns:
        Dictionary of headers to include in webhook request

    Example:
        >>> payload = {"event": "spec.created", "data": {...}}
        >>> headers = generate_signature_headers(payload, WEBHOOK_SECRET)
        >>> requests.post(webhook_url, json=payload, headers=headers)
    """
    headers = {
        SIGNATURE_HEADER: generate_signature(payload, secret),
    }

    if include_timestamp:
        # Add current timestamp as ISO string
        headers["X-Auto-Clause-Timestamp"] = datetime.now(UTC).isoformat()

    return headers


# Convenience functions for common use cases


def sign_webhook_payload(
    payload: dict[str, Any],
    secret: str,
) -> str:
    """
    Sign a webhook payload (convenience function).

    Args:
        payload: JSON payload to sign
        secret: Secret key for signature

    Returns:
        Signature string with version prefix
    """
    return generate_signature(payload, secret)


def check_webhook_signature(
    payload: dict[str, Any],
    signature: str,
    secret: str,
) -> bool:
    """
    Check webhook signature (convenience function).

    This is a simplified version of verify_webhook_signature that
    always returns False instead of raising exceptions.

    Args:
        payload: JSON payload to check
        signature: Signature string from webhook header
        secret: Secret key for verification

    Returns:
        True if signature is valid, False otherwise
    """
    return verify_webhook_signature(payload, signature, secret, raise_on_error=False)
