"""
Runtime abstraction for agent sessions.

This package separates model providers from agent runtimes. Providers create
sessions for model access; runtimes declare what an agent session can safely do
inside an Auto Code workspace.
"""

from .adapters import create_runtime_session
from .adapters.generic_cli import GenericCliRuntimeSession
from .artifacts import (
    save_runtime_fallback_artifact,
    save_runtime_runner_route_artifact,
)
from .capabilities import (
    RuntimeCapabilities,
    RuntimeCapabilityError,
    RuntimePolicy,
    RuntimeRequirements,
)
from .cli_profiles import (
    CLI_RUNNER_PROFILES,
    CliRunnerAvailability,
    CliRunnerProfile,
    CliRunnerRejection,
    CliRunnerSelection,
    cli_runner_profiles_as_dicts,
    detect_cli_runner_availability,
    select_cli_runner_profiles,
)
from .direct_api_autonomy import (
    DIRECT_API_AUTONOMOUS_ENV,
    DIRECT_API_AUTONOMOUS_PROVIDERS,
    DirectApiAutonomousGate,
    direct_api_autonomous_env_enabled,
    resolve_direct_api_autonomous_gate,
)
from .fallback import (
    RUNTIME_FALLBACK_ENV,
    RuntimeFallbackDecision,
    capabilities_for_runtime_mode,
    requirements_for_runtime_mode,
    resolve_runtime_mode_with_fallback,
    runner_candidates_for_modes,
    runtime_fallback_enabled,
)
from .local_actions import (
    LocalActionExecutor,
    LocalActionToolSpec,
    ToolActionResult,
    local_action_response_schema,
    local_action_tool_schemas,
    local_action_tool_specs,
    render_local_action_prompt,
)
from .mcp_bridge import (
    EXTERNAL_MCP_CLIENT_ENV,
    MCP_ALLOWED_PERMISSIONS_ENV,
    MCP_SERVER_CATALOG,
    RuntimeExternalMcpAdapter,
    RuntimeExternalMcpClient,
    RuntimeExternalMcpClientError,
    RuntimeExternalMcpContractCheck,
    RuntimeExternalMcpHttpClient,
    RuntimeExternalMcpServerHealth,
    RuntimeExternalMcpToolDefinition,
    RuntimeMcpBridge,
    RuntimeMcpBridgePlan,
    RuntimeMcpPermissionDecision,
    RuntimeMcpSupport,
    RuntimeMcpToolPolicy,
    RuntimeMcpToolSpec,
    build_external_mcp_health_matrix,
    build_mcp_bridge_plan,
    check_external_mcp_contract,
)
from .mcp_execution_smoke import (
    McpExecutionSmokeResult,
    mcp_execution_smoke,
)
from .mcp_bridge import (
    check_external_mcp_contracts,
    check_mcp_tool_permission,
    describe_external_mcp_server_health,
    describe_mcp_server_statuses,
    executable_external_mcp_servers,
    executable_external_mcp_tools,
    external_mcp_adapter_for,
    external_mcp_client_enabled,
    mcp_bridge_audit_path,
    normalize_mcp_tool_result,
    policy_for_auto_claude_tool,
    registered_external_mcp_servers,
    resolve_runtime_mcp_support,
)
from .modes import RuntimeMode, get_runtime_mode, normalize_runtime_mode
from .result import AgentRunResult
from .runner_router import (
    RUNNER_ROUTER_ENV,
    RuntimeRunnerRoute,
    resolve_runtime_runner_route,
    runtime_runner_router_enabled,
)
from .session_engine import resume_runtime_session, run_runtime_session
from .subagents import (
    MAX_SUBAGENT_ATTEMPTS,
    RuntimeSubagentAttempt,
    RuntimeSubagentOrchestrator,
    RuntimeSubagentResult,
    RuntimeSubagentRun,
    RuntimeSubagentSupport,
    RuntimeSubagentTask,
    build_subagent_merge_plan,
    resolve_runtime_subagent_support,
    summarize_subagent_results,
)

__all__ = [
    "AgentRunResult",
    "RuntimeCapabilities",
    "RuntimeCapabilityError",
    "RuntimeFallbackDecision",
    "RuntimePolicy",
    "RuntimeRequirements",
    "RUNTIME_FALLBACK_ENV",
    "RUNNER_ROUTER_ENV",
    "CLI_RUNNER_PROFILES",
    "EXTERNAL_MCP_CLIENT_ENV",
    "MCP_ALLOWED_PERMISSIONS_ENV",
    "MCP_SERVER_CATALOG",
    "CliRunnerAvailability",
    "CliRunnerProfile",
    "CliRunnerRejection",
    "CliRunnerSelection",
    "GenericCliRuntimeSession",
    "RuntimeMode",
    "DirectApiAutonomousGate",
    "DIRECT_API_AUTONOMOUS_ENV",
    "DIRECT_API_AUTONOMOUS_PROVIDERS",
    "RuntimeExternalMcpClient",
    "RuntimeExternalMcpContractCheck",
    "RuntimeExternalMcpClientError",
    "RuntimeExternalMcpHttpClient",
    "RuntimeExternalMcpAdapter",
    "RuntimeExternalMcpServerHealth",
    "RuntimeExternalMcpToolDefinition",
    "RuntimeMcpBridge",
    "RuntimeMcpBridgePlan",
    "RuntimeMcpPermissionDecision",
    "RuntimeMcpSupport",
    "RuntimeMcpToolPolicy",
    "RuntimeMcpToolSpec",
    "RuntimeRunnerRoute",
    "RuntimeSubagentAttempt",
    "RuntimeSubagentOrchestrator",
    "RuntimeSubagentResult",
    "RuntimeSubagentRun",
    "RuntimeSubagentSupport",
    "RuntimeSubagentTask",
    "LocalActionExecutor",
    "LocalActionToolSpec",
    "ToolActionResult",
    "MAX_SUBAGENT_ATTEMPTS",
    "build_external_mcp_health_matrix",
    "build_mcp_bridge_plan",
    "McpExecutionSmokeResult",
    "mcp_execution_smoke",
    "check_external_mcp_contract",
    "check_external_mcp_contracts",
    "check_mcp_tool_permission",
    "build_subagent_merge_plan",
    "capabilities_for_runtime_mode",
    "cli_runner_profiles_as_dicts",
    "create_runtime_session",
    "detect_cli_runner_availability",
    "describe_external_mcp_server_health",
    "describe_mcp_server_statuses",
    "direct_api_autonomous_env_enabled",
    "executable_external_mcp_servers",
    "executable_external_mcp_tools",
    "external_mcp_adapter_for",
    "external_mcp_client_enabled",
    "get_runtime_mode",
    "local_action_response_schema",
    "local_action_tool_schemas",
    "local_action_tool_specs",
    "mcp_bridge_audit_path",
    "normalize_mcp_tool_result",
    "normalize_runtime_mode",
    "policy_for_auto_claude_tool",
    "registered_external_mcp_servers",
    "render_local_action_prompt",
    "requirements_for_runtime_mode",
    "resolve_runtime_mcp_support",
    "resolve_direct_api_autonomous_gate",
    "resolve_runtime_subagent_support",
    "resolve_runtime_mode_with_fallback",
    "resolve_runtime_runner_route",
    "resume_runtime_session",
    "run_runtime_session",
    "runner_candidates_for_modes",
    "runtime_fallback_enabled",
    "runtime_runner_router_enabled",
    "save_runtime_fallback_artifact",
    "save_runtime_runner_route_artifact",
    "select_cli_runner_profiles",
    "summarize_subagent_results",
]
