#!/bin/bash

# Auto-Build Environment Setup
# Spec: Batch Operations & Quick Actions
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Batch Operations & Quick Actions"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Change to frontend directory
cd apps/frontend

echo ""
echo "Installing dependencies..."
if [ ! -d "node_modules" ]; then
  npm install
  echo -e "${GREEN}✓ Dependencies installed${NC}"
else
  echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To start the development server, run:"
echo ""
echo "  npm run dev"
echo ""
echo "Features to build:"
echo "  - Command palette with Cmd/Ctrl+K"
echo "  - Batch QA operations"
echo "  - Quick actions menu"
echo "  - Keyboard shortcuts customization"
echo "  - GitHub/GitLab quick spec creation"
echo ""
