"""
Custom LLM Provider Plugin Example
===================================

Example integration plugin that demonstrates:
- IntegrationPlugin interface implementation
- Custom LLM provider integration with MCP tools
- Configuration management (API endpoint, API key, model settings)
- State persistence (usage tracking, request count)
- Mock LLM service for demonstration (file-based)
- Build lifecycle hooks

This plugin connects to a mock LLM service and provides MCP tools for agents
to use custom LLM capabilities. It demonstrates how to integrate a custom
LLM provider without requiring actual API credentials.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from plugins.base import PluginMetadata
from plugins.sdk.integration import IntegrationContext, IntegrationPlugin

logger = logging.getLogger(__name__)


class MockLLMClient:
    """
    Mock LLM service client (file-based simulation).

    In a real integration, this would be an HTTP API client to your custom
    LLM service (OpenAI-compatible endpoint, HuggingFace, custom API, etc.)
    """

    def __init__(self, data_dir: Path, endpoint: str, api_key: str, model: str):
        """Initialize the mock LLM client."""
        self.data_dir = data_dir
        self.endpoint = endpoint
        self.api_key = api_key
        self.model = model
        self.usage_file = data_dir / "usage.json"
        self._ensure_data_dir()

    def _ensure_data_dir(self) -> None:
        """Ensure the data directory exists."""
        self.data_dir.mkdir(parents=True, exist_ok=True)
        if not self.usage_file.exists():
            self._save_usage({"total_requests": 0, "total_tokens": 0, "requests": []})

    def _load_usage(self) -> dict:
        """Load usage statistics from file."""
        try:
            with open(self.usage_file, encoding="utf-8") as f:
                return json.load(f)
        except (OSError, json.JSONDecodeError, UnicodeDecodeError) as e:
            logger.error(f"Failed to load usage stats: {e}")
            return {"total_requests": 0, "total_tokens": 0, "requests": []}

    def _save_usage(self, usage: dict) -> None:
        """Save usage statistics to file."""
        try:
            with open(self.usage_file, "w", encoding="utf-8") as f:
                json.dump(usage, f, indent=2)
        except (OSError, UnicodeEncodeError) as e:
            logger.error(f"Failed to save usage stats: {e}")

    def _record_request(self, prompt: str, response: str, tokens: int) -> None:
        """Record a request in usage statistics."""
        usage = self._load_usage()
        usage["total_requests"] += 1
        usage["total_tokens"] += tokens
        usage["requests"].append(
            {
                "timestamp": datetime.now().isoformat(),
                "prompt_length": len(prompt),
                "response_length": len(response),
                "tokens": tokens,
            }
        )
        # Keep only last 100 requests
        usage["requests"] = usage["requests"][-100:]
        self._save_usage(usage)

    def is_connected(self) -> bool:
        """Check if the client is configured and ready."""
        return bool(self.endpoint and self.api_key)

    def complete(
        self, prompt: str, max_tokens: int = 100, temperature: float = 0.7
    ) -> dict:
        """
        Generate text completion.

        In a real implementation, this would make an HTTP request to your
        custom LLM API endpoint.

        Args:
            prompt: Input prompt text
            max_tokens: Maximum tokens to generate
            temperature: Sampling temperature

        Returns:
            Dict with 'text' (completion) and 'tokens' (usage)
        """
        # Mock response based on prompt
        response_text = (
            f"[Mock LLM Response from {self.model}]\n\n"
            f"This is a simulated completion for your prompt. "
            f"In a real implementation, this would be generated by "
            f"your custom LLM service at {self.endpoint}."
        )

        # Simulate token usage
        tokens_used = len(prompt.split()) + len(response_text.split())

        # Record usage
        self._record_request(prompt, response_text, tokens_used)

        logger.info(
            f"Generated completion: {len(response_text)} chars, {tokens_used} tokens"
        )

        return {
            "text": response_text,
            "tokens": tokens_used,
            "model": self.model,
            "timestamp": datetime.now().isoformat(),
        }

    def chat(
        self, messages: list[dict], max_tokens: int = 100, temperature: float = 0.7
    ) -> dict:
        """
        Generate chat completion.

        Args:
            messages: List of message dicts with 'role' and 'content'
            max_tokens: Maximum tokens to generate
            temperature: Sampling temperature

        Returns:
            Dict with 'message' (response) and 'tokens' (usage)
        """
        # Mock response based on last message
        last_message = messages[-1] if messages else {"content": ""}
        user_message = last_message.get("content", "")

        response_message = {
            "role": "assistant",
            "content": (
                f"[Mock LLM Chat Response from {self.model}]\n\n"
                f"I received your message: '{user_message[:50]}...'\n"
                f"In a real implementation, this would be a chat response "
                f"from your custom LLM service."
            ),
        }

        # Simulate token usage
        tokens_used = sum(len(m.get("content", "").split()) for m in messages)
        tokens_used += len(response_message["content"].split())

        # Record usage
        self._record_request(
            user_message, response_message["content"], tokens_used
        )

        logger.info(f"Generated chat response: {tokens_used} tokens")

        return {
            "message": response_message,
            "tokens": tokens_used,
            "model": self.model,
            "timestamp": datetime.now().isoformat(),
        }

    def get_usage_stats(self) -> dict:
        """Get usage statistics."""
        return self._load_usage()


class CustomLLMProviderPlugin(IntegrationPlugin):
    """
    Example custom LLM provider plugin demonstrating IntegrationPlugin capabilities.

    This plugin connects to a mock custom LLM service and provides MCP tools
    for agents to use the LLM for text completion and chat. It demonstrates:
    - Config management (endpoint URL, API key, model name)
    - State persistence (usage tracking)
    - MCP tool creation (complete_text, chat, get_usage)
    - Lifecycle hooks (on_load, on_enable, on_disable, on_unload)
    - Build hooks (on_build_start, on_build_complete, on_subtask_update)
    - External service integration (MockLLMClient)
    """

    def __init__(self, metadata: PluginMetadata):
        """Initialize the custom LLM provider plugin."""
        super().__init__(metadata)
        self.client: Optional[MockLLMClient] = None
        logger.debug("CustomLLMProviderPlugin initialized")

    def on_load(self) -> None:
        """
        Called when plugin is loaded.

        Validates configuration and ensures required settings are present.
        """
        logger.info("custom-llm-provider: Plugin loaded")

        # Validate required configuration
        endpoint = self.get_config_value("CUSTOM_LLM_ENDPOINT")
        api_key = self.get_config_value("CUSTOM_LLM_API_KEY")

        if not endpoint:
            logger.warning(
                "custom-llm-provider: CUSTOM_LLM_ENDPOINT not configured, "
                "using default endpoint"
            )
        if not api_key:
            logger.warning(
                "custom-llm-provider: CUSTOM_LLM_API_KEY not configured, "
                "using default API key"
            )

    def on_enable(self) -> None:
        """
        Called when plugin is enabled.

        Initializes the connection to the custom LLM service.
        """
        logger.info("custom-llm-provider: Plugin enabled")

        # Get configuration from environment
        endpoint = self.get_config_value(
            "CUSTOM_LLM_ENDPOINT", "https://api.example.com/v1"
        )
        api_key = self.get_config_value("CUSTOM_LLM_API_KEY", "sk-demo-key")
        model = self.get_config_value("CUSTOM_LLM_MODEL", "custom-model-v1")
        data_dir_str = self.get_config_value(
            "CUSTOM_LLM_DATA_DIR", "~/.auto-claude/custom-llm"
        )

        # Initialize the mock client
        data_dir = Path(data_dir_str).expanduser()
        self.client = MockLLMClient(data_dir, endpoint, api_key, model)

        logger.info(
            f"custom-llm-provider: Connected to LLM service at {endpoint} "
            f"(model: {model})"
        )

    def on_disable(self) -> None:
        """
        Called when plugin is disabled.

        Disconnects from the LLM service.
        """
        logger.info("custom-llm-provider: Plugin disabled")
        if self.client:
            self.client = None
            logger.debug("custom-llm-provider: Disconnected from LLM service")

    def on_unload(self) -> None:
        """
        Called when plugin is unloaded.

        Cleanup resources and save any final state.
        """
        logger.info("custom-llm-provider: Plugin unloaded")

    def create_mcp_tools(self, context: IntegrationContext) -> list:
        """
        Create MCP tools for this integration.

        These tools will be available to agents during sessions, allowing them
        to use the custom LLM provider for text generation tasks.

        Args:
            context: Integration context with project/spec information

        Returns:
            List of MCP tool definitions (function name, handler, schema)
        """
        if not self.client:
            logger.warning("custom-llm-provider: Client not initialized")
            return []

        def complete_text(prompt: str, max_tokens: int = 100) -> dict:
            """
            Generate text completion using the custom LLM.

            Args:
                prompt: Input prompt text
                max_tokens: Maximum tokens to generate (default: 100)

            Returns:
                Dict with completion text, tokens used, and metadata
            """
            logger.info(f"custom-llm-provider: Completing text: '{prompt[:50]}...'")
            result = self.client.complete(prompt, max_tokens=max_tokens)
            return result

        def chat_with_llm(messages: list[dict], max_tokens: int = 100) -> dict:
            """
            Generate chat completion using the custom LLM.

            Args:
                messages: List of message dicts with 'role' and 'content' keys
                max_tokens: Maximum tokens to generate (default: 100)

            Returns:
                Dict with response message, tokens used, and metadata
            """
            logger.info(
                f"custom-llm-provider: Chat with {len(messages)} messages"
            )
            result = self.client.chat(messages, max_tokens=max_tokens)
            return result

        def get_llm_usage() -> dict:
            """
            Get usage statistics for the custom LLM provider.

            Returns:
                Dict with total requests, total tokens, and recent requests
            """
            logger.info("custom-llm-provider: Getting usage statistics")
            stats = self.client.get_usage_stats()
            return {
                "total_requests": stats.get("total_requests", 0),
                "total_tokens": stats.get("total_tokens", 0),
                "recent_requests": len(stats.get("requests", [])),
            }

        # MCP tool definitions
        tools = [
            {
                "name": "custom_llm_complete",
                "description": "Generate text completion using custom LLM provider",
                "handler": complete_text,
                "schema": {
                    "type": "object",
                    "properties": {
                        "prompt": {
                            "type": "string",
                            "description": "Input prompt text",
                        },
                        "max_tokens": {
                            "type": "integer",
                            "description": "Maximum tokens to generate",
                            "default": 100,
                        },
                    },
                    "required": ["prompt"],
                },
            },
            {
                "name": "custom_llm_chat",
                "description": "Generate chat completion using custom LLM provider",
                "handler": chat_with_llm,
                "schema": {
                    "type": "object",
                    "properties": {
                        "messages": {
                            "type": "array",
                            "description": "List of chat messages with role and content",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "role": {"type": "string"},
                                    "content": {"type": "string"},
                                },
                                "required": ["role", "content"],
                            },
                        },
                        "max_tokens": {
                            "type": "integer",
                            "description": "Maximum tokens to generate",
                            "default": 100,
                        },
                    },
                    "required": ["messages"],
                },
            },
            {
                "name": "custom_llm_usage",
                "description": "Get usage statistics for custom LLM provider",
                "handler": get_llm_usage,
                "schema": {
                    "type": "object",
                    "properties": {},
                },
            },
        ]

        logger.info(f"custom-llm-provider: Created {len(tools)} MCP tools")
        return tools

    def on_build_start(
        self, context: IntegrationContext, spec_name: str
    ) -> None:
        """
        Called when a build starts.

        Args:
            context: Integration context
            spec_name: Name of the spec being built
        """
        logger.info(
            f"custom-llm-provider: Build started for spec '{spec_name}'"
        )

    def on_build_complete(
        self, context: IntegrationContext, spec_name: str, success: bool
    ) -> None:
        """
        Called when a build completes.

        Args:
            context: Integration context
            spec_name: Name of the spec that was built
            success: Whether the build succeeded
        """
        status = "succeeded" if success else "failed"
        logger.info(
            f"custom-llm-provider: Build {status} for spec '{spec_name}'"
        )

        # Log usage statistics at end of build
        if self.client:
            stats = self.client.get_usage_stats()
            logger.info(
                f"custom-llm-provider: LLM usage during build: "
                f"{stats.get('total_requests', 0)} requests, "
                f"{stats.get('total_tokens', 0)} tokens"
            )

    def on_subtask_update(
        self,
        context: IntegrationContext,
        subtask_id: str,
        status: str,
    ) -> None:
        """
        Called when a subtask status changes.

        Args:
            context: Integration context
            subtask_id: ID of the subtask
            status: New status (pending, in_progress, completed, failed)
        """
        logger.debug(
            f"custom-llm-provider: Subtask {subtask_id} -> {status}"
        )
