#!/bin/bash

# Auto-Build Environment Setup
# Feature: UX Feedback Loop - Visual Annotation System
# Generated by Planner Agent

set -e

echo "========================================"
echo "UX Annotation System - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to frontend
FRONTEND_DIR="apps/frontend"

if [ ! -d "$FRONTEND_DIR" ]; then
    echo -e "${RED}Error: Frontend directory not found: $FRONTEND_DIR${NC}"
    exit 1
fi

# Check if npm dependencies are installed
if [ ! -d "$FRONTEND_DIR/node_modules" ]; then
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    cd "$FRONTEND_DIR"
    npm install
    cd ../..
fi

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo "Starting Frontend (Electron + Vite)..."
echo ""

cd "$FRONTEND_DIR"

# Start dev server (Vite + Electron)
npm run dev &
DEV_PID=$!

# Wait for dev server to start
echo "Waiting for dev server to initialize..."
sleep 5

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  Electron app (Vite dev server)"
echo ""
echo "Note: Annotation mode is only available in dev mode."
echo "  - Look for annotation toggle in toolbar"
echo "  - Enable to start marking UI areas"
echo ""
echo "Process ID: $DEV_PID"
echo "Press Ctrl+C to stop"
echo ""

# Wait for process to finish
wait $DEV_PID
